chatgpt-shell.el
chatgpt-shell-transmitted-context-length controls the amount of context provided to chatGPT.
Context needs to be transmitted to the API on every request, which consumes a lot of prompt tokens as the conversation gets longer.
A value of `nil' will send "full" chat history (last 4096 messages at max), which is near enough how it was before the patch, and is the default value.
A value of 0 will not provide any context.  This is the cheapest option, but ChatGPT can only see your current prompt.  A value of 1 will send only the latest prompt-completion pair as context.  Values greater than 1 will send that amount of prompt-completion pairs to ChatGPT.
=> Configuration `chatgpt-shell-transmitted-context-length'

README.org
This adds an alternative snippet in the README showing how you can provide credentials in a secure way by relying on emacs's auth-sources library.
I'm not trying to clutter the beautiful simplicity of this project, so please feel free to reject this if you think it's more noise than signal. It was helpful to me so I thought I'd suggest it!
=> Add README snippet on using auth-sources for credentials

chatgpt-shell.el
Use completing read pre-populated with some example prompts. Works nicely with vertico etc.
=> Use completing-read in chatgpt-shell-chatgpt-prompt

dall-e-shell.el
* chatgpt-shell/dall-e-shell.el: ** new `dall-e-shell-image-output-directory`
** modified `dall-e-shell--extract-response`
=> Customizable directory for the generated image

README.org
Personally, I prefer using
``` elisp
(auth-source-pass-get 'secret "openai-key")
```
over
``` elisp
(nth 0 (process-lines "pass" "show" "openai-key")
```
`auth-source-pass-get` is included in the built-in `auth-sources` library starting from Emacs 26 and autoloaded from Emacs 27.
The already documented `auth-source-pick-first-password`  already works with pass if you add `password-store` to `auth-sources`, therefore there's an argument that we already have documentation how to use `auth-sources`. But `auth-source-pass-get` works out-of-the-box without customizing the `auth-sources` variable and its interface is different than using `auth-source-pick-first-password` with the `password-store` backend. `auth-source-pass-get` wants the entire path to the password like `pass`, e.g. I have …
=> Document `auth-source-pass-get` alternative to get secrets from pass

shell-maker.el
This commit adds `shell-maker-history-path` as a `defcustom` for shell-maker, which lets the end user tell shell-maker to store all history files for all derived shells in a location other than `user-emacs-directory`; `user-emacs-directory` is kept as the default.
=> Add a custom variable for setting the root location for history

README.org
Just a simple typo fix in readme.org file
=> Typofix README.org

README.org
Simple typofix for several function and variable names.
BTW it would be nice to document what "streaming" means exactly in the context of chatgpt.
=> Drop superfluous "chatgpt" from several symbol names in README.org

shell-maker.el
I was confused when I tried out this package and I would type my prompt and hit enter and nothing would happen. The issue was that I have split out the terminal codes from the key chords in my Emacs so that `C-m` is separate from `RET`. This meant that hitting enter was not mapping to correct function. 
This change will keep the keybindings consistent with whatever the user has set in their `comint-mode`, so everything "just works".
=> Remap existing comint-mode keybindings

README.org, chatgpt-shell.el
Two parts constructed URL string to suit more situations.
Fix #73
=> Make ChatGPT API customize option from two parts.

chatgpt-shell.el
I want to customize prompts for some functions.
Because I want to communicate with ChatGPT in Japanese.
So I extracted some prompt headers to `defcustom` variables.
What do you this about these?
```elisp
(custom-set-variables
;; "What does the following code do?"
'(chatgpt-shell-prompt-header-describe-code "以下のコードはどのような意味ですか？"))
```
=> Extract some prompt headers to defcustom variables

chatgpt-shell.el
- OpenAI announced new version of ChatGPT models: https://openai.com/blog/function-calling-and-other-api-updates
- And some current versions are deprecated:
- `gpt-3.5-turbo-0301`
- `gpt-4-0314`
- So, we need to upgrade model versions: 
- `gpt-3.5-turbo-0613`
- `gpt-4-0613`
- I am currently unable to access GPT-4 by API
- So I could not test `gpt-4-0613` model by `chatgpt-shell`
=> Upgrade model versions

chatgpt-shell.el
Addresses a few of the chatgpt-shell functions returning errors about not being in a shell because the major mode was changed to `chatgpt-shell-mode` and they expected `shell-maker-mode`
=> Changes some references to `shell-maker-mode` to `chatgpt-shell-mode`

shell-maker.el
I sometimes need to type multiple line input, but it seems that there is no simple way to do it. (Please correct me if I'm wrong)
This PR simply adds a default keybinding for `newline`. I believe `S-<return>` is somewhat standard for inserting newline when `<return>` was occupied.
=> Allow for multiline input

README.org, ob-chatgpt-shell.el
Summary: This diff adds support for multiple different contexts using org-babel src blocks. The context is specified using the source block's `:context` param, which can be any string.
Test Plan: If you put the source blocks below in an org file and execute the last block it should return a response similar to `sir/madam` as opposed to `human` given the last block specified "lawyer" as opposed to "robot".
```
#+BEGIN_SRC chatgpt-shell :context lawyer :system "From here on out speak as if you're a bloviating old-timey lawyer." :results code 
How do you do?
#+END_SRC
#+RESULTS:
#+begin_src chatgpt-shell
Well now, I do declare, I am as fine as a frog's hair split three ways and sanded smooth. I am as content as a cucumber in a summer salad, basking in the warm embrace of the southern sun. I …
```
=> Add support handle multiple org-babel contexts

shell-maker.el
See #122 
Addresses an issue where invoking `chatgpt-shell` resulted in error `shell-maker-start: Invalid function: shell-maker--with-temp-buffer-if`
Moving the new macros to the top of the file solves the issue. I think this is related to byte-compilation:
> In order for compilation of macro calls to work, the macros must already be defined in Lisp when the calls to them are compiled. The compiler has a special feature to help you do this: if a file being compiled contains a defmacro form, the macro is defined temporarily for the rest of the compilation of that file.
https://www.gnu.org/software/emacs/manual/html_node/elisp/Compiling-Macros.html
=> moves macros above defuns that call them

chatgpt-shell.el, dall-e-shell.el
Without UTF-8 support, you cannot effectively use this interface with languages such as German, French, and others. The responses are not properly displayed when there are characters with diacritical marks involved (such as German umlauts).
=> Add UTF-8 support to HTTP requests and responses

chatgpt-shell.el
Still keeping the 4K Context version since it's double the price to use the higher context window version. Ideally the shell would switch to the higher context version automatically.
https://openai.com/pricing
=> Update chatgpt-shell-model-versions to include 16K context for GPT-3.5 Turbo

chatgpt-shell.el
- Added new GPT4-Turbo model identifier `gpt-4-1106-preview` to `chatgpt-shell-model-versions` function.
=> Add GPT4-Turbo model version

chatgpt-shell.el
This improves the ability to edit this using customize
This is a first commit for #167.
That said, it may make more sense to consider a type as follows:
```elisp
'(alist :key-type regexp
:value-type function)
```
and use regular expression matching (thus only one entry for Objective C) to get the mode directly.
=> Update the customization type of `chatgpt-shell-language-mapping`

dall-e-shell.el
Introduce new customization `dall-e-shell-image-quality' and use it in `dall-e-shell--make-payload'.
=> dall-e-shell.el: Add support for image quality

chatgpt-shell.el
The function `chatgpt-shell-restore-session-from-transcript` does not current specify the directory when reading the filename of the transcript to restore. This can be a bit inconvenient for users as they will usually have to navigate to `shell-maker-transcript-default-path` manually each time. This PR fixes that issue.
=> Add default directory for restoring transcripts

chatgpt-shell.el
commit 03afa73 updated `shell-maker-history-path` to `shell-maker-root-path`
=> alias chatgpt-shell-historty-path to the new shell-maker variable

chatgpt-shell.el
=> Explicitly specify UTF-8 encoding for temporary file in Windows

chatgpt-shell.el, shell-maker.el
Try to implement the issue #227 .
After `(setf shell-maker-if-file-path-reset-after-clean 'reset)` and manually binding the `("C-c M-o" . chatgpt-shell-clear-buffer)`. It will reset the `shell-maker--file`to `nil` after I clean the buffer. So I can save the new conversation in new file. 
**Feel free to change it if it isn't match the design of **owner.**
=> Draft: Reset the file path after clean the buffer

README.org, chatgpt-shell-ollama.el, chatgpt-shell.el
+ add ollama url base 
+ fix one source code block issue.
Sometimes the source code in "```" cannot match perfectly like: 
```
1. this is some thing
and this is the line start from space
```elisp
upper one is good 
next "```" cannot match as the end of this source code block, because it start with spaces
```
```
So the highlight and the code copy/paste feature is confusing. 
(I am not sure I changed all "```" match in this PR, but I test with my case and it looks good. Feel free to change this PR)
=> Custom ollama url base and source code block issue

chatgpt-shell-openai.el
The context length for OpenAI models is 128K according to OpenAI's documentation. However, the current code uses 12800 (12.8K) instead.
=> Fix context length for OpenAI models

chatgpt-shell-ollama.el
This is a basic implementation of chatgpt-shell-ollama-load-models. I've tested it lightly and it seems to work at least for my ollama setup.
=> Initial implementation of chatgpt-shell-ollama-load-models

chatgpt-shell-google.el
I cant find the `:path` in google's doc (they don't give the rest call example), I just make my best guess, looks like I am lucky. 
*I just tested on my machine*
=> Add gemini-2.0-flash-exp

chatgpt-shell-openai.el, chatgpt-shell-openrouter.el, chatgpt-shell.el
This adds support for various llama and qwen models via OpenRouter. It also adds support for OpenAI's o1 model which is currently only available to teir 5 API users.
=> Openrouter

chatgpt-shell.el
This is for consistency with other shell-style buffers in Emacs
=> Put the whole chatgpt shell buffer name inside the earmuffs

chatgpt-shell.el
Annoyingly, I accidently put the '*' before the ')' in the last pull request. 😠
=> Fix transposed characters in buffer name

chatgpt-shell.el
`chatgpt-shell-root-path` is already defined as an alias for `shell-maker-root-path`. I'm per-se fine with that, although I could also see that some might prefer it even independently configurable. In any case, this is currently unused.
Make chatgpt respect the `chatgpt-shell-root-path` when creating internal files like `.chatgpt-shell.el`.
Use case: I want to keep a tidy `emacs.d` with my configuration and auto-generated files clearly separated.
=> Make chatgpt-shell respect `chatgpt-shell-root-path`

chatgpt-shell-openrouter.el
Using only `defun` results in errors during byte compilation:
```
Compiling file /home/ad/git/chatgpt-shell/chatgpt-shell-openrouter.el at Thu Jan  2 20:14:24 2025
chatgpt-shell-openrouter.el:123:2: Error: Garbage following &rest VAR in lambda-list
```
=> Use cl-defun in openrouter for &key params

chatgpt-shell.el
Fixed a problem that caused `args-out-of-range` errors when calling `chatgpt-shell-proofread-region` while narrowing.
This is the same modification I suggested in #297.
=> Avoid args-out-of-range errors in match-string calls

chatgpt-shell-openrouter.el
o1, o3-mini and o3-mini-high are now all useable through OpenRouter without a high-teir OpenAI API key (which was previously required). A high-teir API key still seems to be required to use them through OpenAI directly.
=> Add o3-mini models (which are now usable through OR)

chatgpt-shell-deepseek.el, chatgpt-shell-openai.el
The previous code only had DeepSeek Chat. This adds DeepSeek Reasoner (which currently points to DeepSeek R1). See
https://api-docs.deepseek.com/quick_start/pricing.
=> Add DeepSeek reasoner

chatgpt-shell-anthropic.el
Like OpenAI and Google, Anthropic provides models with the suffix "-latest" that point to the newest version of each of their models (e.g. Sonnet-3.7, Sonnet-3.5, etc.). Avoiding using versions tagged with a specific date reduces the need to update the models as new releases are made and is in line with what is already in place for Google and OpenAI models.
=> Use the latest versions for Anthropic models instead of dated versions

chatgpt-shell.el
This is useful for keeping redundant models (like openrouter "o3-mini" which is also available more cheaply through openai) in the models list but enabling users to hide them if they don't need them at the moment.
=> Add the ability to ignore some model versions when swapping

chatgpt-shell-google.el, chatgpt-shell.el
Discover Gemini models via the API. 
This requires an API key, so it may need a fallback if you'd like the "fixed list" to work when no API key is available.
=> feat: discover Gemini models dynamically via API

chatgpt-shell-google.el
Previously experimental models for gemini were only available with the date in the model version. However, it is now possible to always use the latest version.
=> Add experimental version of gemini 2.0 pro and use latest versions

chatgpt-shell-google.el
This fixes #325 .
The `chatgpt-shell-google--fetch-model-versions` fn loads model descriptions from Google via a GET to https://generativelanguage.googleapis.com/v1beta/models 
The response is a set of records like the following. 
```
{
"name": "models/gemini-2.0-flash-exp",
"version": "2.0",
"displayName": "Gemini 2.0 Flash Experimental",
"description": "Gemini 2.0 Flash Experimental",
"inputTokenLimit": 1048576,
"outputTokenLimit": 8192,
"supportedGenerationMethods": [
"generateContent",
"countTokens",
"bidiGenerateContent"
],
"temperature": 1,
"topP": 0.95,
"topK": 40,
"maxTemperature": 2
},
```
In cases in which the model is deprecated, the `description` field has contained the word "deprecated".  so the logic in 
`chatgpt-shell-google--fetch-model-versions`  filters out such records. …
=> fix: handle case where google model lacks description

chatgpt-shell-openai.el
Just noticed there are several changes on openai API side:
+ `chatgpt-4o-latest` document link change to [https://platform.openai.com/docs/models/chatgpt-4o-latest](https://platform.openai.com/docs/models/chatgpt-4o-latest) 
+ [https://platform.openai.com/docs/models/gpt-4o](https://platform.openai.com/docs/models/gpt-4o) link to the other model gpt-4o
Several changes:
+ `gpt-4o` is much cheaper, so I move it to be the first option than `chatgpt-4o-latest`
+ also add the `gpt-4o-mini`
+ added two models those can search web `gpt-4o-search-preview` and `gpt-4o-mini-search-preview`
=> Change some openai models and add new models

chatgpt-shell-google.el
This is the same model as 2.5 pro experimental. The difference is that it has higher rate limits but is also paid.
=> Add Gemini 2.5 pro preview

chatgpt-shell.el
Thanks for your package.
Here is a small tweak to `chatgpt-shell-proofread-region` to decrease friction: if no region is active, mark paragraph and proofread this paragraph. Since this function is likely to be run paragraph by paragraph, this removes the need for selecting a paragraph.
=> Transform chatgpt-shell-proofread-region to a DWIM approach

chatgpt-shell.el
You are right. It is useful to rename the function. Here is the PR.
Thanks for merging so quickly.
Note that there is one tiny default to what I proposed. When proofreading a paragraph, if the AI suggestion is rejected, instead of the point staying at its original position, the point is moved to the beginning of the paragraph and the paragraph is marked. I have tried a few things, but I was not able to solve this, but this is a minor issue that I can live with.
=> Rename proofread function, and add alias for old name

README.org
**Now that this file exists:**
https://github.com/xenodium/shell-maker/blob/main/markdown-overlays.el
The instructions that only include the `shell-maker.el` file are insufficient to actually install the whole package. As currently written - running `chatgpt-shell` yields the following error:
```
Please update 'shell-maker' to v0.77.1 or newer
```
**Other thought:**
You may want to change the name of the `markdown-overlays.el` file such that it's namespaced like `shell-maker-markdown-overlays` - in which case, the current instructions and the files remain explicit. That's, of course, up to you!
**Addendum:**
Thanks for an amazing blog and a million awesome packages.
I love your work 🎉
=> Update shell-maker install instructions in README

README.org, chatgpt-shell-transient.el, chatgpt-shell.el
Closes #341 
Here's the new transient menu!
How it looks **outside** the chatgpt-shell buffer:
How it looks in the `chatgpt-shell` buffer (`C-c C-t` by default):
How it looks on region selection:
Some videos:
General demo:
https://github.com/user-attachments/assets/7bf30c6f-b248-4033-a564-bcbd5d83c9dc
Region selection demo:
https://github.com/user-attachments/assets/b37f71f2-edb3-467d-b49b-d87d0fc151d9
=> Add transient menu

chatgpt-shell-transient.el, chatgpt-shell.el
This PR addresses a lazy loading issue with the `transient` package. Previously, the `chatgpt-shell-transient` functionality, which defines the transient popup menu for `chatgpt-shell`, was not wrapped in `with-eval-after-load`. This could lead to errors if `transient` was not fully loaded before `chatgpt-shell-transient.el` was evaluated.
The fix involves encapsulating the `transient-define-prefix` and `transient-define-suffix` calls within an `(with-eval-after-load 'transient ...)` block. This ensures that the transient definitions are only evaluated after the `transient` package has been loaded, preventing potential initialization errors.
Additionally, the `Package-Requires` in `chatgpt-shell.el` has been updated to explicitly include `transient` with a minimum version of "0.9.3", …
=> Add correct transient dependency
