chatgpt-shell.el
https://github.com/purcell/package-lint
=> Fix warnings from package-lint

chatgpt-shell.el
This commit makes the used language model and temperature parameter user-configurable.  OpenAI API reference requires that the temperature be between 0 and 2.  A `nil' value here will not pass anything to the model, instead the default value, which is currently 1, will be used.
API documentation is available at:
- https://platform.openai.com/docs/models/model-endpoint-compatibility
- https://platform.openai.com/docs/api-reference/completions/create#completions/create-temperature
=> defcustom for language model and temperature

chatgpt-shell.el
Not an expert on Elisp so this one might be a miss: I thought it might be neat to have the image size configurable, otherwise those credits pile up quickly. :)
=> make the requested DALL-E image size customizable

chatgpt-shell.el
=> Add functions for code / text improving

README.org
Update auth source comment to correct host.
=> Update auth source comment in README

chatgpt-shell.el
Fixes #94 
It looks like the order was out of place. This PR allows the function to be defined before it's used.
=> Fix void function error

README.org
tesolved -> resolved (re: dependencies in melpa vs. straight)
=> fixes typo in README.org

chatgpt-shell.el
Add a function to quickly create git commits from highlighted region.  
1) Highlight region
2) Create commit
3) Push
=> Add chatgpt-shell-write-git-commit function

chatgpt-shell.el
There are a couple of emacs CSV parsing libraries that seem to handle quoted fields and embedded commas. This PR plugs in one of those.
(BTW - the "ignoring empty prompts" filter of the previous impl doesn't seem needed, so left it out as YAGNI)
Fixes: #126
=> Switch to using a real csv parser

chatgpt-shell.el
=> Allow customize type for chatgpt-shell-system-prompt to be nil

dall-e-shell.el
The modification is similar to chatgpt-shell-additional-curl-options in chatgpt-shell
=> add dall-e-shell-additional-curl-options like chatgpt-shell

chatgpt-shell.el
=> Improve documentation and customization type for babel headers

chatgpt-shell.el
=> Update type of chatgpt-shell-source-block-actions

chatgpt-shell.el
=> Update type of chatgpt-shell-system-prompts

shell-maker.el
This one just provides the default option, and a common option as something that can be easily selected using customize.
=> Improve type of shell-maker-display-function

README.org, chatgpt-shell.el
Fix #155. 
@xenodium Also need to test against OpenAI GPT before merging.
The following cases need to be considered for the Azure GPT streaming response:
- `choices` is empty
- No `delta` key
- No `content` key in `delta`
This PR returns an empty string for above cases.
An example of the streaming response:
```
data: {"id":"","object":"","created":0,"model":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}],"choices":[]}
data: {"id":"chatcmpl-8V1mzvFANVW81eY6AMkrEgfIMuFKN","object":"chat.completion.chunk","created":1702405737,"model":"gpt-4","choices":[{"index":0,"finish_reason":nul …
```
=> Fix no results from Azure GPT when stream is enabled

dall-e-shell.el
Also did tiny tiny refactor (let me know if it make sense please)
@xenodium PTAL Thanks.
=> Add function to generate image from selected text

chatgpt-shell.el
=> add new gpt models announced in 2024-01-25

README.org
- Updates readme to add a section to set API key from Environment Variable
=> Readme set API key from Environment Variable

chatgpt-shell.el, test_chatgpt-shell.el
=> add some test code, tiny refactoring and util function

README.org
Add instructions to README for launching concurrent shells with =C-u M-x chatgpt-shell=.
=> Add insstructions for launching concurrent additional shells.

chatgpt-shell.el
=> Create .chatgpt-shell.el if it does not exist

chatgpt-shell.el
Add the `chatgpt-4o-latest`, `o1` models.
And update the `chatgpt-shell--approximate-context-length` with new models.
=> Add new model and update the max-tokens

chatgpt-shell.el
#235 
The bug fix on my side after this PR's change.
=> Fix the incorrect override issue

chatgpt-shell-anthropic.el
Update the Sonnet model to the latest version `claude-3-5-sonnet-20241022` [1].
Also add the latest available Haiku and Opus models.
[1] https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table
=> Update sonnet, add haiku and opus

chatgpt-shell.el
Parse the CSV retrieved from Awesome Prompts [1] on our own. This
removes the dependency on the pcsv package which is not standard.
While there is certainly an argument to be made against NIH, CSV parsing
should also be do-able with reasonable added complexity, at least if the
format is somewhat well-known. A dependency on a third party package
just for this seems unnecessary.
The pcsv parser was added in response to issue #126. I am using this parser
suggested here in claude-shell [2] since quite a while and it worked
well enough - and as far as I can tell also correct.
[1] https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv
[2] https://github.com/arminfriedl/claude-shell
=> Roll own csv parsing, remove `pcsv` dependency

chatgpt-shell-google.el
Use the latest version of gemini-1.5-flash (as is already done for gemini-1.5-pro).
=> Use the latest version of gemini-1.5-flash

chatgpt-shell-google.el
Add gemini-exp-1206. This is an early release of gemini-2.0-pro which has some impressive benchmarks. Also adds a reasoning version of gemini-2.0-flash. 
https://livebench.ai/#/
=> Add experimental gemini models

chatgpt-shell-anthropic.el
Adding the recent Claude model.
=> Add Anthropic's Claude 3.7 Sonnet model.

chatgpt-shell-ollama.el
=> Use chatgpt-shell-request-timeout in requests to ollama

chatgpt-shell-openrouter.el
Simple add. Did it mostly because I wanted to use anthropic through open router and though it should be good to contribute to this nice project :)
=> added anthropic to open router

chatgpt-shell.el
add support for a custom selector, `chatgpt-shell-swap-model-selector`, to use within `chatgpt-shell-swap-model` . 
When a user wants to take advantage of this, they might use something like this: 
```
(defun my-custom-cgs-model-sort (candidates) (sort candidates :lessp #'string<))
(defun my-custom-cgs-model-completion-table (candidates)
"Returns a function to be used as the COMPLETIONS parameter in
`completing-read'"
(lexical-let ((candidates candidates)) ;; if necessary
(lambda (string pred action)
(if (eq action 'metadata)
`(metadata
(cycle-sort-function . ,#'my-custom-cgs-model-sort)
(display-sort-function . ,#'my-custom-cgs-model-sort))
(complete-with-action action candidates string pred)))))
(setq chatgpt-shell-swap-model-selector
(lambda (candidates)
(completing-read "New model: " …
```
=> feat: optional custom selector when swapping models

chatgpt-shell-google.el
=> add gemini-2.5-pro-exp

README.org
Just some small changes to clarify.
=> Readme tweaks

chatgpt-shell-anthropic.el
More detailed description of extended thinking in
* https://support.anthropic.com/en/articles/10574485-using-extended-thinking-on-claude-3-7-sonnet
* https://docs.anthropic.com/en/docs/about-claude/models/extended-thinking-models#extended-output-capabilities-beta
=> Use extended thinking on Claude 3.7 Sonnet

chatgpt-shell-openrouter.el
Problem:
Tokens are being dropped when using OpenRouter models #374
Root cause:
Fragmented JSON chunks and ": OPENROUTER PROCESSING" spam in the streaming output.
Solution:
Process streaming output line-by-line with a temporary buffer
Concat received ":pending" with new output
Drop lines that start with ":" - "OPENROUTER..." spam
Only process complete "data: {...}"
Incomplete lines are passed as :pending for the next cycle
=> Fix openrouter filter output function

chatgpt-shell-anthropic.el
Claude Sonnet 4.5 got released 29.09.2025
It is basically compatible with Sonnet 4 just supposedly better
Announcement:
https://www.anthropic.com/news/claude-sonnet-4-5
Docs:
https://docs.claude.com/en/docs/about-claude/models/overview
=> Add Claude Sonnet 4.5
